# Final Project
## Data exploration
### James Fallon

In [1]:
import pandas as pd
import numpy as np

import glob

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [38]:
files = glob.glob('LC Data/LoanStats3[a-d].csv.zip')
files2 = glob.glob('LC Data/LoanStats_2016Q[1-2].csv.zip')
files = files + files2

print 'IMPORT LOAN DATA\n'
print 'files being imported:\n' + str(files) +'\n'

#keep track of concatenation
i = 0

#start with the first file
data = pd.read_csv(files[0], header = 1, compression = 'zip')
print 'file ' + str(i) + ' complete'

#loop through remaining files
for file in files[1:len(files)]:
    
    data = pd.concat((data, pd.read_csv(file, header = 1, compression = 'zip')), axis = 0)
    
    #keep track of loading process
    i+=1
    print 'file ' + str(i) + ' complete'
    
    if i == len(files):
        print 'import complete'

#sense check shape, size etc. of dataset
np.shape(data)
variables = pd.DataFrame(data.columns.values)
data.index.values
data.head(n=5)

files being imported:
['LC Data/LoanStats3a.csv.zip', 'LC Data/LoanStats3b.csv.zip', 'LC Data/LoanStats3c.csv.zip', 'LC Data/LoanStats3d.csv.zip', 'LC Data/LoanStats_2016Q1.csv.zip', 'LC Data/LoanStats_2016Q2.csv.zip']

file 0 complete
file 1 complete
file 2 complete
file 3 complete
file 4 complete
file 5 complete

(1119194, 111)

array([    0,     1,     2, ..., 97853, 97854, 97855])

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,1077501,1296599.0,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
1,1077430,1314167.0,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
2,1077175,1313524.0,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
3,1076863,1277178.0,10000.0,10000.0,10000.0,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,1075358,1311748.0,3000.0,3000.0,3000.0,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN

In [45]:
#import declined loan data

files = ['LC Data/RejectStatsB.csv.zip', 'LC Data/RejectStatsD.csv.zip']
files2 = glob.glob('LC Data/RejectStats_2016Q[1-2].csv.zip')
files = files + files2

print 'IMPORT DECLINED LOAN DATA\n'
print 'files being imported:\n' + str(files) +'\n'

#keep track of concatenation
i = 0

#start with the first file
dec_data = pd.read_csv(files[0], header = 1, compression = 'zip')
print 'file ' + str(i) + ' complete'

#loop through remaining files
for file in files[1:len(files)]:
    
    dec_data = pd.concat((dec_data, pd.read_csv(file, header = 1, compression = 'zip')), axis = 0)
    
    #keep track of loading process
    i+=1
    print 'file ' + str(i) + ' complete'
    
    if i == len(files):
        print 'import complete'

#sense check shape, size etc. of dataset
np.shape(dec_data)
dec_variables = pd.DataFrame(dec_data.columns.values)
dec_data.index.values
dec_data.head(n=5)

IMPORT DECLINED LOAN DATA

files being imported:
['LC Data/RejectStatsB.csv.zip', 'LC Data/RejectStatsD.csv.zip', 'LC Data/RejectStats_2016Q1.csv.zip', 'LC Data/RejectStats_2016Q2.csv.zip']

file 0 complete
file 1 complete
file 2 complete
file 3 complete

(7645772, 9)

array([     0,      1,      2, ..., 996359, 996360, 996361])

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
0,30000.0,2013-01-01,debt_consolidation,754.0,32.01%,559xx,MN,< 1 year,0.0
1,15000.0,2013-01-01,medical,728.0,27.01%,945xx,CA,< 1 year,0.0
2,2500.0,2013-01-01,other,723.0,0.92%,190xx,PA,7 years,0.0
3,4000.0,2013-01-01,car,563.0,24.92%,296xx,SC,< 1 year,0.0
4,22000.0,2013-01-01,debt_consolidation,0.0,26.91%,735xx,OK,< 1 year,0.0